# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_code', models.IntegerField()),
                ('major', models.CharField(max_length=100)),
                ('major_category', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('employed', models.IntegerField()),
                ('employed_full_time_year_round', models.IntegerField()),
                ('unemployed', models.IntegerField()),
                ('unemployment_rate', models.FloatField()),
                ('median', models.IntegerField()),
                ('p25th', models.IntegerField()),
                ('p75th', models.IntegerField()),
            ],
        ),
    ]
